### PR TITLE
Feat: first iteration of upgrading Gatsby to latest version 5.

### PR DESCRIPTION
**Pull request by maanasb01**
This PR is related to issue #183 

Please use `npm install --legacy-peer-deps` to install the dependencies

### CODE REVIEW

**Comment by dennyabrain** [comment]
@maanasb01 the netlify build seems to be failing because it was using older version of node to build the site. I have upgraded node version on netlify. You might need to push again to trigger a build. Since its a major commit, I'd like to make sure the preview build on netlify is passing so i can test all important pages.

**Comment by maanasb01** [comment]
@dennyabrain Done!

**Comment by maanasb01** [comment]
@dennyabrain It appears that the version which is being used is still 16.20.2

Netlify Build logs:
image

**Comment by dennyabrain** [comment]
Yeah, not sure why. I have configured netlify to use the latest stable node version.



Lets take a lookk tomorrow.

**Comment by maanasb01** [comment]
@dennyabrain Yeah sure! Can it depend on [deploy-production.yml](https://github.com/tattle-made/website/blob/master/.github/workflows/deploy-production.yml) file? In that file, the mentioned node version is still 16.

**Comment by dennyabrain** [comment]
Hmmm, I don't think so. But regardless I have updated the version in the workflow file as well and merged in main.

**Comment by maanasb01** [comment]
@dennyabrain Yeah you were right, it did not work. I pushed a new commit and it failed again with the same error (the version compatibility one).

**Comment by dennyabrain** [comment]
I have pulled the PR locally and built it and checked it. I am merging it to check the possiblity that maybe netlify is failing because of some old data/caching issue. Will watch out for next PR

**Comment by maanasb01** [comment]
Great! Glad it worked out!

**Pull request merged**
